[build]
    command = "npm install"
    functions = "functions/"

[[redirects]]
    from = "/api-docs/*"
    to = "/.netlify/functions/server/:splat"
    status = 200

[[headers]]
    for = "/.netlify/functions/server/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"
        Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
        Access-Control-Allow-Headers = "Content-Type, Authorization, Accept, X-Requested-With"

[functions]
    node_bundler = "esbuild"
    external_node_modules = ["mongoose", "dotenv"]
    included_files = ["functions/**"]